### ISSUE TITLE
Show animations properly in Telegram

### ISSUE THREAD

**Issue by shelbyKiraM** [FirraWoof/xfuraffinity#2]
Right now xfuraffinity takes a post of an animation: [https://xfuraffinity.net/view/50542051/](https://xfuraffinity.net/view/50542051/) for example and just returns a static image to Telegram. It does show it as a gif in Discord. Maybe do it like video embeds for (again the embed ninja stuff I use the most) vxtwitter?

**Comment by FirraWoof** [comment]
I'll definitely see what I can do about this, the tricky thing is that Telegram doesn't render previews that are bigger than around 5MB in size or so, so currently if the source file on FA is too large, the thumbnail is shown in Telegram (but the original is sent in Discord).

I'd just have to test things out a bit to see if Telegram actually renders gifs that are bigger than 5MB, or maybe find a workaround 🤔

**Comment by shelbyKiraM** [comment]
I do know Telegram treats MP4 with no audio track as a gif... Does FA optimise gifs to MP4?

**Comment by shelbyKiraM** [comment]
Ahhh also, the direct GIF link embeds properly in Telegram.

**Comment by FirraWoof** [comment]
Interesting, maybe they don't have that size limitation for gifs, I'll hopefully be able to do some testing over the weekend!

**Comment by shelbyKiraM** [comment]
So in testing of a page I know works, like, everywhere, yeah we need an MP4 version of the gif which I still can't find they generate in FA… try `curl https://giphy.com/gifs/animation-ah-yes-the-three-genders-via-youtube-pHZa5vmEZtnzzaX2E0` to see what giphy thinks is best for meta tags.

**Comment by FirraWoof** [comment]
Unfortunately FA doesn't generate an MP4 version, and after more testing, it looks like there's definitely some weirdness going on with Telegram's GIF embedding. Even the [share link](https://media.giphy.com/media/pHZa5vmEZtnzzaX2E0/giphy-downsized.gif) from giphy doesn't work, and I'm not sure why since it seems to be a direct link to a GIF that's below 5MB.

However, I managed to figure out a solution by luck while I was doing some trial and error, so it should work now, thankfully.

For the record, the way giphy works is by using an MP4, so they kinda bypass this issue. For their share links that only use the GIF, it also doesn't work, which makes me suspect nobody really knows about this maybe 🤔

**Comment by shelbyKiraM** [comment]
Submit issue in https://github.com/TelegramMessenger/Telegram-iOS ? Or another of their repos?

**Comment by shelbyKiraM** [comment]
Also, hehe: you don't support Mosaic‽!‽!! 😆 http://webaim.org/blog/user-agent-string-history/

**Comment by FirraWoof** [comment]
> Submit issue in https://github.com/TelegramMessenger/Telegram-iOS ? Or another of their repos?

Not sure, I don't think they handle embeds in the clients, there's no mention of any of the metadata tags in their desktop client at least

> Also, hehe: you don't support Mosaic‽!‽!! 😆 http://webaim.org/blog/user-agent-string-history/

The user agents you see in the project are only the different bots that should be given an embed! So if you clicked on an `xfuraffinity.net` link with Mosaic, it should redirect you to `furaffinity.net` as expected I think!
